import { SITE } from './content.js'

const en = {
  meta: {
    title: 'Aetherion — Minecraft MMO · donnernet.de',
    description:
      'Aetherion is a Minecraft MMO of islands, skills, quests and dungeons. Join play.donnernet.de — or spin up your own free sandbox server in a minute.',
  },
  nav: {
    features: 'Features',
    world: 'World',
    playground: 'Playground',
    support: 'Support',
    main: 'Main navigation',
    mobile: 'Mobile navigation',
    menuOpen: 'Open menu',
    menuClose: 'Close menu',
    menu: 'Menu',
    copyIp: 'Copy IP',
    signIn: 'Sign in',
    myServers: 'My servers',
    signOut: 'Sign out',
    account: 'Account',
  },
  hero: {
    badge: 'Pre-beta · Java Edition',
    statusLoading: 'Checking the network…',
    statusOnline: '{n} playing right now',
    statusOnlineOne: '1 player online',
    statusQuiet: 'Online · be the first today',
    statusOffline: 'Network is restarting',
    line: 'An MMO of islands, skills and dungeons.',
    sub: 'Level real skills, sail between islands, run bosses with friends. Nothing that makes you stronger is for sale.',
    ipLabel: 'Server address',
    edition: 'Java {version} · Velocity',
    copy: 'Copy',
    copied: 'Copied',
    ipCopied: 'IP copied — paste it in Minecraft',
    copyTitle: 'Copy server IP',
    play: 'Play now',
    launcher: 'Get the launcher',
    launcherHint: 'Windows · installs the pack for you',
    howTo: 'Minecraft Java → Multiplayer → Add Server → {ip}',
  },
  facts: [
    { value: '5', label: 'Skills to master' },
    { value: '4', label: 'Skill islands in Eldervale' },
    { value: '3+', label: 'Dungeon floors with bosses' },
    { value: '1.21.1', label: 'Java Edition' },
  ],
  features: {
    kicker: 'The game',
    title: 'What awaits you',
    sub: 'Every system is custom-built for Aetherion.',
    items: {
      skills: {
        title: 'Skills',
        sub: 'Combat · Mining · Farming · Fishing · Foraging',
        body: 'Five skills with real progression: tiered tools, gear sets and charms you unlock by playing, managed from the Aetherion Manager.',
      },
      islands: {
        title: 'Islands',
        sub: 'Eldervale & the satellite isles',
        body: 'Fields, fishing grounds, Forage Isle and the mining island — linked by slime jump pads that arc you from shore to shore.',
      },
      amethyst: {
        title: 'Amethyst Mines',
        sub: 'The Veins',
        body: 'Crystal halls deep under the islands. Compacted ores, boosters and the Veins — mining is its own adventure here.',
      },
      quests: {
        title: 'Quests & NPCs',
        sub: 'Egon, Ledger, Vex, Lark …',
        body: 'Story quests with dialogue, compass markers and rewards that open up the world — from your first catch to your first boss.',
      },
      dungeons: {
        title: 'Dungeons & bosses',
        sub: 'Instances · phases · boss drops',
        body: 'Private instances with phased bosses like the Ashen Sheath. Their weapons drop — they are never sold.',
      },
      market: {
        title: 'Player economy',
        sub: 'Auction House & Bazaar',
        body: 'Trade with other players instead of a cash shop. Coins are earned, prices are set by the people who play.',
      },
    },
  },
  rarity: {
    common: 'Common',
    uncommon: 'Uncommon',
    rare: 'Rare',
    epic: 'Epic',
    legendary: 'Legendary',
    mythic: 'Mythic',
  },
  world: {
    kicker: 'The world',
    title: 'Places you will know by heart',
    sub: 'From your first step at the harbour to the throne of the third floor.',
    soon: 'Screenshot coming soon',
    items: {
      harbour: {
        title: 'Anker Harbour',
        sub: 'Spawn · docks · market',
        caption: 'Everyone starts here. Egon waits on the pier, the market is up the stairs, the islands are across the water.',
      },
      throne: {
        title: 'Throne of Ashes',
        sub: 'Dungeon · Floor 3',
        caption: 'Lava halls, ash and a boss that does not give up its katana easily.',
      },
      eldervale: {
        title: 'Eldervale',
        sub: 'The island cluster',
        caption: 'Farming, fishing, foraging and mining islands past the jump pads — the heart of the skill loop.',
      },
      amethyst: {
        title: 'Amethyst Mines',
        sub: 'The Veins',
        caption: 'Crystal halls and deep veins. Bring a good pickaxe.',
      },
    },
  },
  playground: {
    kicker: 'Playground',
    title: 'Your own Minecraft server. Free, in a minute.',
    body: 'Test a build, try a version, play with two friends. Create as many worlds as you like — one runs at a time, on the same hardware as Aetherion.',
    points: [
      'Pick RAM from 512 MB to 2 GB',
      'Paper, Vanilla, Purpur or Fabric',
      'Live console, one-click start and stop',
    ],
    cta: 'Create a free server',
    ctaAuthed: 'Open my servers',
    note: 'Only a username and a password. No email.',
    previewName: 'Weekend Build',
    previewNameB: 'Modded Test',
  },
  support: {
    kicker: 'Support shop',
    title: 'Shards for friends',
    sub: 'PayPal first. Shards are granted by hand.',
    bannerKicker: 'Optional · not pay-to-win',
    bannerTitle: 'Support is a prototype thank-you. Not required to play. Nobody has to pay to be strong.',
    bannerBody: 'Shards do not buy power, dungeon wins, or skill levels. If you never donate, you still play the same server.',
    packs: {
      starter: { label: 'Starter', hint: 'A small thanks' },
      freund: { label: 'Friend', hint: 'Better rate' },
      patron: { label: 'Patron', hint: 'Best rate' },
    },
    customTitle: 'Custom amount',
    customBody: '€1–999. Shards by arrangement — no automaton, no rate promise outside the packs.',
    amountLabel: 'Amount in euro',
    shards: 'Shards',
    openPaypal: 'Open PayPal',
    customInvalid: 'Please choose an amount between 1 and 999 euro.',
    fulfillTitle: 'Credit v1 — manual after PayPal',
    fulfill: [
      'Send a pack or amount via PayPal to {email}.',
      'Open Discord and DM the team: Minecraft name (IGN) + PayPal receipt.',
      'We credit Shards by hand. There is no auto-shop and no webhooks yet.',
    ],
    toDiscord: 'To Discord',
    bankTitle: 'Bank transfer — friends only',
    bankOpen: 'Show',
    bankClose: 'Hide',
    bankBody: 'IBAN (SEPA). Payment reference: your IGN + “Shards”. Still send a Discord DM with the receipt afterwards.',
    copyIban: 'Copy IBAN',
    ibanCopied: 'IBAN copied',
  },
  finale: {
    title: 'See you at the harbour.',
    body: 'Open Minecraft Java, add the server, and Egon will take it from there.',
  },
  footer: {
    blurb: 'A Minecraft MMO network by a small team of friends. Join at {ip}.',
    shop: 'Support shop',
    world: 'World',
    playground: 'Playground',
    servers: 'My servers',
    launcher: 'Launcher',
    legal:
      'Aetherion is a private fan network and is not affiliated with Mojang Studios or Microsoft. Minecraft is a trademark of Mojang Studios. Not approved by Mojang or Microsoft.',
  },
  ui: {
    copied: 'Copied',
    copy: 'Copy',
    langEn: 'English',
    langDe: 'German',
    langToggle: 'Language',
    close: 'Close',
    cancel: 'Cancel',
    retry: 'Try again',
    loading: 'Loading…',
    offline: 'Connection lost — reconnecting…',
  },
  app: {
    auth: {
      signInTitle: 'Welcome back',
      signInSub: 'Sign in to manage your servers.',
      registerTitle: 'Create your account',
      registerSub: 'A username and a password. That is all.',
      username: 'Username',
      usernameHint: '3–20 characters: letters, numbers, . - _',
      password: 'Password',
      passwordHint: 'At least 8 characters.',
      show: 'Show',
      hide: 'Hide',
      signIn: 'Sign in',
      register: 'Create account',
      noAccount: 'New here?',
      haveAccount: 'Already have an account?',
      createOne: 'Create an account',
      signInInstead: 'Sign in',
      welcome: 'Welcome, {name}!',
      welcomeBack: 'Signed in as {name}',
      signedOut: 'Signed out',
      required: 'Required',
    },
    status: {
      preparing: 'Preparing',
      failed: 'Setup failed',
      offline: 'Offline',
      starting: 'Starting',
      online: 'Online',
      stopping: 'Stopping',
      restarting: 'Restarting',
    },
    servers: {
      title: 'My servers',
      sub: 'Create as many worlds as you like. One can run at a time.',
      create: 'Create server',
      slotLabel: 'Running slot',
      slotFree: 'Free — start any of your servers.',
      slotUsed: '{name} is {status}.',
      slotManage: 'Manage',
      manage: 'Manage',
      start: 'Start',
      stop: 'Stop',
      switchHere: 'Switch to this',
      switchTitle: 'Switch servers?',
      switchBody: '“{from}” will stop (players are disconnected, the world is saved) and “{to}” starts.',
      switchConfirm: 'Stop & start',
      switching: 'Switching…',
      players: '{online}/{max} players',
      emptyTitle: 'No servers yet',
      emptyBody: 'Create your first world. It takes about a minute until you can join.',
      emptyCta: 'Create your first server',
      loadError: 'Your servers could not be loaded.',
      created: 'Created {date}',
    },
    create: {
      back: 'My servers',
      title: 'Create a server',
      sub: 'Three choices, then you can play.',
      name: 'Server name',
      namePlaceholder: 'Weekend Build',
      nameHint: 'Only you see this name. 2–32 characters.',
      ram: 'Memory',
      ramNote: 'Smaller tiers are meant for lightweight tests with one or two players. Modpacks need far more than 2 GB.',
      recommended: 'Recommended',
      tiers: {
        512: 'Solo tests · vanilla',
        768: 'You and a friend',
        1024: 'Small groups',
        1536: 'Plugins & bigger worlds',
        2048: 'Most headroom',
      },
      software: 'Software',
      softwareHints: {
        paper: 'Fast, plugin-ready. Best default.',
        vanilla: 'Pure Minecraft, exactly as Mojang ships it.',
        purpur: 'Paper with extra gameplay options.',
        fabric: 'Mod loader base for Fabric setups.',
      },
      version: 'Minecraft version',
      latest: 'latest',
      startNow: 'Start it right away',
      startNowHint: 'You can join as soon as it is online.',
      startBlocked: '“{name}” is running, so this one is created stopped. Start it whenever you like.',
      summary: 'Summary',
      summaryIdle: 'Stops by itself after {n} minutes without players.',
      summaryLimit: 'One server can run at a time.',
      submit: 'Create server',
      submitting: 'Creating…',
      poolLow: 'The shared pool is busy right now. Creating works, starting may have to wait.',
      loadError: 'Options could not be loaded.',
    },
    dash: {
      back: 'My servers',
      address: 'Address',
      copyAddress: 'Copy address',
      addressCopied: 'Address copied',
      start: 'Start',
      stop: 'Stop',
      restart: 'Restart',
      switchHere: 'Switch to this server',
      blockedBy: '“{name}” is using your running slot.',
      startingHint: 'Booting Minecraft — usually 20–40 seconds.',
      stoppingHint: 'Saving the world and shutting down.',
      preparingHint: 'Downloading the server files.',
      failedHint: 'The server files could not be prepared.',
      stats: {
        players: 'Players',
        memory: 'Memory',
        cpu: 'CPU',
        uptime: 'Uptime',
        version: 'Version',
        allocated: '{ram} allocated',
        noPlayers: 'Nobody online',
        offline: '—',
      },
      idleNote: 'Stops automatically after {n} minutes without players.',
      idleCountdown: 'Nobody is online — stopping in {n} min.',
      join: {
        title: 'How to join',
        steps: ['Open Minecraft Java Edition {version}', 'Multiplayer → Add Server', 'Paste the address and join'],
      },
      tabs: { console: 'Console', settings: 'Settings' },
      addons: {
        plugins: 'Plugins',
        mods: 'Mods',
        vanilla: 'Vanilla servers cannot load plugins or mods. Create a Paper or Purpur server for plugins, or Fabric for mods.',
        installedTitle: 'Installed {kind} ({n})',
        none: 'No {kind} installed yet.',
        browse: '{kind} for Minecraft {version}',
        search: 'Search {kind} on Modrinth',
        poweredBy: 'via Modrinth',
        install: 'Install',
        remove: 'Remove',
        downloads: '{n} downloads',
        installed: '{name} installed',
        removed: '{name} removed',
        noBuild: 'No build for Minecraft {version} yet.',
        empty: 'Nothing found for Minecraft {version}.',
        searchError: 'Modrinth could not be reached. Try again in a moment.',
        restartHint: 'Restart the server to load your changes.',
      },
      console: {
        placeholder: 'Type a command, e.g. op {name}',
        send: 'Send',
        offline: 'Start the server to use the console.',
        empty: 'No output yet.',
        follow: 'Follow',
        sent: 'Command sent',
      },
      settings: {
        name: 'Server name',
        motd: 'Message of the day',
        motdHint: 'Shown in the Minecraft server list.',
        difficulty: 'Difficulty',
        gamemode: 'Default game mode',
        maxPlayers: 'Max players',
        ram: 'Memory',
        ramLocked: 'Stop the server to change its memory.',
        save: 'Save changes',
        saving: 'Saving…',
        saved: 'Settings saved',
        applyNote: 'World settings apply on the next start.',
        difficulties: { peaceful: 'Peaceful', easy: 'Easy', normal: 'Normal', hard: 'Hard' },
        gamemodes: { survival: 'Survival', creative: 'Creative', adventure: 'Adventure', spectator: 'Spectator' },
      },
      danger: {
        title: 'Danger zone',
        body: 'Deleting removes the server and its world for good. This cannot be undone.',
        delete: 'Delete server',
        confirmTitle: 'Delete “{name}”?',
        confirmBody: 'The world, settings and console history are removed permanently. Type the server name to confirm.',
        confirm: 'Delete forever',
        deleting: 'Deleting…',
        deleted: 'Server deleted',
      },
      setup: {
        title: 'Setting up your server',
        steps: ['Server created', 'Downloading server files', 'Starting Minecraft', 'Online'],
        readyTitle: 'Your server is online',
        readyBody: 'Add it in Minecraft and start playing.',
        stoppedTitle: 'Your server is ready',
        stoppedBody: 'Press Start when you want to play.',
      },
      notices: {
        IDLE_STOPPED: 'Stopped automatically because nobody was online.',
        START_FAILED: 'The server stopped while starting. The console shows why.',
        RUNNING_LIMIT: 'Created, but not started: another server was running.',
        POOL_FULL: 'Created, but not started: the shared pool was full. Try Start again in a bit.',
      },
      notFound: 'This server does not exist or belongs to someone else.',
    },
    errors: {
      RUNNING_LIMIT: 'Only one server can run at a time. Stop the other one first.',
      RUNNING_LIMIT_NAMED: 'Only one server can run at a time. Stop “{name}” first.',
      POOL_FULL: 'All shared server capacity is in use right now. Try again in a few minutes.',
      NO_PORTS: 'No free server slots on the host right now. Try again later.',
      PREPARING: 'The server files are still downloading. It will be ready in a moment.',
      SETUP_FAILED: 'Setup failed for this server. Delete it and create a new one.',
      NOT_RUNNING: 'The server is not running.',
      MUST_BE_OFFLINE: 'Stop the server before changing its memory.',
      NOT_READY: 'The server files are not ready yet. Try again in a moment.',
      BUSY: 'The server is still shutting down. Try again in a minute.',
      ADDON_INCOMPATIBLE: 'That build does not fit this server’s software or version.',
      ADDON_TOO_LARGE: 'That file is too large.',
      ADDONS_UNSUPPORTED: 'Vanilla servers cannot load plugins or mods.',
      INVALID_LOGIN: 'Wrong username or password.',
      USERNAME_TAKEN: 'That username is taken.',
      INVALID_USERNAME: 'Usernames are 3–20 characters: letters, numbers, dot, dash or underscore.',
      INVALID_PASSWORD: 'Passwords need at least 8 characters.',
      INVALID_NAME: 'Server names need 2–32 characters.',
      INVALID_TIER: 'Pick one of the memory tiers.',
      INVALID_VERSION: 'That Minecraft version is not available.',
      INVALID_SOFTWARE: 'Pick a server software.',
      RATE_LIMITED: 'Too many attempts. Wait a moment and try again.',
      RATE_LIMITED_WAIT: 'Too many attempts. Try again in {min} min.',
      UNAUTHORIZED: 'Your session ended. Please sign in again.',
      NOT_FOUND: 'Not found.',
      FORBIDDEN: 'That request was blocked.',
      VALIDATION: 'Please check your input.',
      UPSTREAM: 'The server host did not answer. Try again in a moment.',
      NETWORK: 'No connection. Check your internet and try again.',
      GENERIC: 'Something went wrong. Try again.',
    },
  },
  notFound: {
    code: '404',
    title: 'This chunk never generated',
    body: 'The page you are looking for is not part of this world.',
    home: 'Back to the harbour',
    servers: 'My servers',
  },
}

const de = {
  meta: {
    title: 'Aetherion — Minecraft-MMO · donnernet.de',
    description:
      'Aetherion ist ein Minecraft-MMO mit Inseln, Skills, Quests und Dungeons. Join play.donnernet.de — oder starte in einer Minute deinen eigenen kostenlosen Sandbox-Server.',
  },
  nav: {
    features: 'Features',
    world: 'Welt',
    playground: 'Playground',
    support: 'Support',
    main: 'Hauptnavigation',
    mobile: 'Mobilnavigation',
    menuOpen: 'Menü öffnen',
    menuClose: 'Menü schließen',
    menu: 'Menü',
    copyIp: 'IP kopieren',
    signIn: 'Anmelden',
    myServers: 'Meine Server',
    signOut: 'Abmelden',
    account: 'Konto',
  },
  hero: {
    badge: 'Pre-Beta · Java Edition',
    statusLoading: 'Prüfe das Netzwerk …',
    statusOnline: '{n} spielen gerade',
    statusOnlineOne: '1 Spieler online',
    statusQuiet: 'Online · sei heute der Erste',
    statusOffline: 'Netzwerk startet neu',
    line: 'Ein MMO aus Inseln, Skills und Dungeons.',
    sub: 'Echte Skills leveln, zwischen Inseln reisen, Bosse mit Freunden laufen. Nichts, was dich stärker macht, ist käuflich.',
    ipLabel: 'Server-Adresse',
    edition: 'Java {version} · Velocity',
    copy: 'Kopieren',
    copied: 'Kopiert',
    ipCopied: 'IP kopiert — in Minecraft einfügen',
    copyTitle: 'Server-IP kopieren',
    play: 'Jetzt spielen',
    launcher: 'Launcher holen',
    launcherHint: 'Windows · installiert das Pack für dich',
    howTo: 'Minecraft Java → Mehrspieler → Server hinzufügen → {ip}',
  },
  facts: [
    { value: '5', label: 'Skills zum Meistern' },
    { value: '4', label: 'Skill-Inseln in Eldervale' },
    { value: '3+', label: 'Dungeon-Floors mit Bossen' },
    { value: '1.21.1', label: 'Java Edition' },
  ],
  features: {
    kicker: 'Das Spiel',
    title: 'Was dich erwartet',
    sub: 'Jedes System ist eigens für Aetherion gebaut.',
    items: {
      skills: {
        title: 'Skills',
        sub: 'Combat · Mining · Farming · Fishing · Foraging',
        body: 'Fünf Skills mit echtem Fortschritt: Werkzeug-Stufen, Gear-Sets und Charms, die du dir erspielst — alles im Aetherion Manager.',
      },
      islands: {
        title: 'Inseln',
        sub: 'Eldervale & die Satelliten-Inseln',
        body: 'Felder, Angelgründe, Forage Isle und die Mining-Insel — verbunden durch Slime-Jump-Pads, die dich von Ufer zu Ufer tragen.',
      },
      amethyst: {
        title: 'Amethyst-Minen',
        sub: 'The Veins',
        body: 'Kristallhallen tief unter den Inseln. Verdichtete Erze, Booster und die Veins — Mining ist hier ein eigenes Abenteuer.',
      },
      quests: {
        title: 'Quests & NPCs',
        sub: 'Egon, Ledger, Vex, Lark …',
        body: 'Story-Quests mit Dialogen, Kompass-Markern und Belohnungen, die dir die Welt öffnen — vom ersten Fang bis zum ersten Boss.',
      },
      dungeons: {
        title: 'Dungeons & Bosse',
        sub: 'Instanzen · Phasen · Boss-Drops',
        body: 'Eigene Instanzen mit Phasen-Bossen wie dem Ashen Sheath. Ihre Waffen droppen — verkauft werden sie nie.',
      },
      market: {
        title: 'Spieler-Wirtschaft',
        sub: 'Auction House & Bazaar',
        body: 'Handel mit anderen Spielern statt Cash-Shop. Coins werden verdient, Preise machen die Leute, die spielen.',
      },
    },
  },
  rarity: {
    common: 'Gewöhnlich',
    uncommon: 'Ungewöhnlich',
    rare: 'Selten',
    epic: 'Episch',
    legendary: 'Legendär',
    mythic: 'Mythisch',
  },
  world: {
    kicker: 'Die Welt',
    title: 'Orte, die du bald auswendig kennst',
    sub: 'Vom ersten Schritt am Hafen bis zum Thron im dritten Floor.',
    soon: 'Screenshot folgt',
    items: {
      harbour: {
        title: 'Anker Harbour',
        sub: 'Spawn · Docks · Markt',
        caption: 'Hier startet jeder. Egon wartet am Steg, der Markt liegt die Treppe hoch, die Inseln hinter dem Wasser.',
      },
      throne: {
        title: 'Throne of Ashes',
        sub: 'Dungeon · Floor 3',
        caption: 'Lavahallen, Asche und ein Boss, der sein Katana nicht einfach hergibt.',
      },
      eldervale: {
        title: 'Eldervale',
        sub: 'Der Insel-Cluster',
        caption: 'Farming-, Fishing-, Foraging- und Mining-Inseln hinter den Jump-Pads — das Herz des Skill-Loops.',
      },
      amethyst: {
        title: 'Amethyst-Minen',
        sub: 'The Veins',
        caption: 'Kristallhallen und tiefe Adern. Nimm eine gute Spitzhacke mit.',
      },
    },
  },
  playground: {
    kicker: 'Playground',
    title: 'Dein eigener Minecraft-Server. Kostenlos, in einer Minute.',
    body: 'Build testen, Version ausprobieren, mit zwei Freunden spielen. Erstelle so viele Welten, wie du willst — eine läuft gleichzeitig, auf derselben Hardware wie Aetherion.',
    points: [
      'RAM von 512 MB bis 2 GB wählen',
      'Paper, Vanilla, Purpur oder Fabric',
      'Live-Konsole, Start und Stopp mit einem Klick',
    ],
    cta: 'Kostenlosen Server erstellen',
    ctaAuthed: 'Meine Server öffnen',
    note: 'Nur Benutzername und Passwort. Keine E-Mail.',
    previewName: 'Wochenend-Build',
    previewNameB: 'Modded-Test',
  },
  support: {
    kicker: 'Support-Shop',
    title: 'Shards für Freunde',
    sub: 'Zuerst PayPal. Shards werden von Hand gutgeschrieben.',
    bannerKicker: 'Optional · kein Pay-to-Win',
    bannerTitle: 'Support ist ein Prototyp-Danke. Nicht nötig zum Spielen. Niemand muss zahlen, um stark zu sein.',
    bannerBody: 'Shards kaufen keine Power, keine Dungeon-Wins, keine Skill-Level. Wer nicht spendet, spielt denselben Server.',
    packs: {
      starter: { label: 'Starter', hint: 'Kleines Danke' },
      freund: { label: 'Freund', hint: 'Besserer Kurs' },
      patron: { label: 'Patron', hint: 'Bester Kurs' },
    },
    customTitle: 'Freier Betrag',
    customBody: '€1–999. Shards nach Absprache — kein Automat, kein Kurs-Versprechen außerhalb der Packs.',
    amountLabel: 'Betrag in Euro',
    shards: 'Shards',
    openPaypal: 'PayPal öffnen',
    customInvalid: 'Bitte einen Betrag zwischen 1 und 999 Euro wählen.',
    fulfillTitle: 'Gutschrift v1 — manuell nach PayPal',
    fulfill: [
      'Pack oder Betrag per PayPal an {email} senden.',
      'Discord öffnen und dem Team per DM schreiben: Minecraft-Name (IGN) + PayPal-Beleg.',
      'Wir buchen die Shards von Hand. Es gibt noch keinen Auto-Shop und keine Webhooks.',
    ],
    toDiscord: 'Zum Discord',
    bankTitle: 'Banküberweisung — nur für Freunde',
    bankOpen: 'Aufklappen',
    bankClose: 'Zuklappen',
    bankBody: 'IBAN (SEPA). Verwendungszweck: dein IGN + „Shards“. Danach trotzdem Discord-DM mit Beleg.',
    copyIban: 'IBAN kopieren',
    ibanCopied: 'IBAN kopiert',
  },
  finale: {
    title: 'Wir sehen uns am Hafen.',
    body: 'Minecraft Java öffnen, Server hinzufügen — ab da übernimmt Egon.',
  },
  footer: {
    blurb: 'Ein Minecraft-MMO-Netzwerk von einem kleinen Freundes-Team. Join: {ip}.',
    shop: 'Support-Shop',
    world: 'Welt',
    playground: 'Playground',
    servers: 'Meine Server',
    launcher: 'Launcher',
    legal:
      'Aetherion ist ein privates Fan-Netzwerk und steht in keiner Verbindung zu Mojang Studios oder Microsoft. Minecraft ist eine Marke von Mojang Studios. Nicht von Mojang oder Microsoft genehmigt.',
  },
  ui: {
    copied: 'Kopiert',
    copy: 'Kopieren',
    langEn: 'Englisch',
    langDe: 'Deutsch',
    langToggle: 'Sprache',
    close: 'Schließen',
    cancel: 'Abbrechen',
    retry: 'Nochmal versuchen',
    loading: 'Lädt …',
    offline: 'Verbindung verloren — verbinde neu …',
  },
  app: {
    auth: {
      signInTitle: 'Willkommen zurück',
      signInSub: 'Melde dich an, um deine Server zu verwalten.',
      registerTitle: 'Konto erstellen',
      registerSub: 'Benutzername und Passwort. Mehr nicht.',
      username: 'Benutzername',
      usernameHint: '3–20 Zeichen: Buchstaben, Zahlen, . - _',
      password: 'Passwort',
      passwordHint: 'Mindestens 8 Zeichen.',
      show: 'Zeigen',
      hide: 'Verbergen',
      signIn: 'Anmelden',
      register: 'Konto erstellen',
      noAccount: 'Neu hier?',
      haveAccount: 'Schon ein Konto?',
      createOne: 'Konto erstellen',
      signInInstead: 'Anmelden',
      welcome: 'Willkommen, {name}!',
      welcomeBack: 'Angemeldet als {name}',
      signedOut: 'Abgemeldet',
      required: 'Pflichtfeld',
    },
    status: {
      preparing: 'Wird vorbereitet',
      failed: 'Setup fehlgeschlagen',
      offline: 'Offline',
      starting: 'Startet',
      online: 'Online',
      stopping: 'Stoppt',
      restarting: 'Startet neu',
    },
    servers: {
      title: 'Meine Server',
      sub: 'Erstelle so viele Welten, wie du willst. Eine kann gleichzeitig laufen.',
      create: 'Server erstellen',
      slotLabel: 'Laufender Slot',
      slotFree: 'Frei — starte einen deiner Server.',
      slotUsed: '{name} ist {status}.',
      slotManage: 'Verwalten',
      manage: 'Verwalten',
      start: 'Starten',
      stop: 'Stoppen',
      switchHere: 'Hierher wechseln',
      switchTitle: 'Server wechseln?',
      switchBody: '„{from}“ wird gestoppt (Spieler fliegen raus, die Welt wird gespeichert) und „{to}“ startet.',
      switchConfirm: 'Stoppen & starten',
      switching: 'Wechsle …',
      players: '{online}/{max} Spieler',
      emptyTitle: 'Noch keine Server',
      emptyBody: 'Erstelle deine erste Welt. Nach etwa einer Minute kannst du joinen.',
      emptyCta: 'Ersten Server erstellen',
      loadError: 'Deine Server konnten nicht geladen werden.',
      created: 'Erstellt am {date}',
    },
    create: {
      back: 'Meine Server',
      title: 'Server erstellen',
      sub: 'Drei Entscheidungen, dann geht’s los.',
      name: 'Servername',
      namePlaceholder: 'Wochenend-Build',
      nameHint: 'Nur du siehst diesen Namen. 2–32 Zeichen.',
      ram: 'Arbeitsspeicher',
      ramNote: 'Kleine Stufen sind für leichte Tests mit ein, zwei Spielern gedacht. Modpacks brauchen deutlich mehr als 2 GB.',
      recommended: 'Empfohlen',
      tiers: {
        512: 'Solo-Tests · Vanilla',
        768: 'Du und ein Freund',
        1024: 'Kleine Gruppen',
        1536: 'Plugins & größere Welten',
        2048: 'Am meisten Luft',
      },
      software: 'Software',
      softwareHints: {
        paper: 'Schnell, plugin-fähig. Die beste Wahl.',
        vanilla: 'Reines Minecraft, genau wie von Mojang.',
        purpur: 'Paper mit zusätzlichen Gameplay-Optionen.',
        fabric: 'Mod-Loader-Basis für Fabric-Setups.',
      },
      version: 'Minecraft-Version',
      latest: 'neueste',
      startNow: 'Direkt starten',
      startNowHint: 'Du kannst joinen, sobald er online ist.',
      startBlocked: '„{name}“ läuft gerade, deshalb wird dieser gestoppt erstellt. Starte ihn, wann du willst.',
      summary: 'Übersicht',
      summaryIdle: 'Stoppt von selbst nach {n} Minuten ohne Spieler.',
      summaryLimit: 'Ein Server kann gleichzeitig laufen.',
      submit: 'Server erstellen',
      submitting: 'Erstelle …',
      poolLow: 'Der gemeinsame Pool ist gerade ausgelastet. Erstellen geht, Starten muss evtl. kurz warten.',
      loadError: 'Optionen konnten nicht geladen werden.',
    },
    dash: {
      back: 'Meine Server',
      address: 'Adresse',
      copyAddress: 'Adresse kopieren',
      addressCopied: 'Adresse kopiert',
      start: 'Starten',
      stop: 'Stoppen',
      restart: 'Neustart',
      switchHere: 'Zu diesem Server wechseln',
      blockedBy: '„{name}“ belegt deinen Laufslot.',
      startingHint: 'Minecraft bootet — meist 20–40 Sekunden.',
      stoppingHint: 'Welt wird gespeichert und heruntergefahren.',
      preparingHint: 'Server-Dateien werden heruntergeladen.',
      failedHint: 'Die Server-Dateien konnten nicht vorbereitet werden.',
      stats: {
        players: 'Spieler',
        memory: 'Speicher',
        cpu: 'CPU',
        uptime: 'Laufzeit',
        version: 'Version',
        allocated: '{ram} zugewiesen',
        noPlayers: 'Niemand online',
        offline: '—',
      },
      idleNote: 'Stoppt automatisch nach {n} Minuten ohne Spieler.',
      idleCountdown: 'Niemand online — stoppt in {n} Min.',
      join: {
        title: 'So joinst du',
        steps: ['Minecraft Java Edition {version} öffnen', 'Mehrspieler → Server hinzufügen', 'Adresse einfügen und beitreten'],
      },
      tabs: { console: 'Konsole', settings: 'Einstellungen' },
      addons: {
        plugins: 'Plugins',
        mods: 'Mods',
        vanilla: 'Vanilla-Server können keine Plugins oder Mods laden. Erstelle einen Paper- oder Purpur-Server für Plugins oder Fabric für Mods.',
        installedTitle: 'Installierte {kind} ({n})',
        none: 'Noch keine {kind} installiert.',
        browse: '{kind} für Minecraft {version}',
        search: '{kind} auf Modrinth suchen',
        poweredBy: 'über Modrinth',
        install: 'Installieren',
        remove: 'Entfernen',
        downloads: '{n} Downloads',
        installed: '{name} installiert',
        removed: '{name} entfernt',
        noBuild: 'Noch kein Build für Minecraft {version}.',
        empty: 'Nichts gefunden für Minecraft {version}.',
        searchError: 'Modrinth ist gerade nicht erreichbar. Versuch es gleich nochmal.',
        restartHint: 'Starte den Server neu, damit deine Änderungen geladen werden.',
      },
      console: {
        placeholder: 'Befehl eingeben, z. B. op {name}',
        send: 'Senden',
        offline: 'Starte den Server, um die Konsole zu nutzen.',
        empty: 'Noch keine Ausgabe.',
        follow: 'Mitscrollen',
        sent: 'Befehl gesendet',
      },
      settings: {
        name: 'Servername',
        motd: 'Nachricht des Tages',
        motdHint: 'Wird in der Minecraft-Serverliste angezeigt.',
        difficulty: 'Schwierigkeit',
        gamemode: 'Standard-Spielmodus',
        maxPlayers: 'Max. Spieler',
        ram: 'Arbeitsspeicher',
        ramLocked: 'Stoppe den Server, um den Speicher zu ändern.',
        save: 'Speichern',
        saving: 'Speichere …',
        saved: 'Einstellungen gespeichert',
        applyNote: 'Welt-Einstellungen greifen beim nächsten Start.',
        difficulties: { peaceful: 'Friedlich', easy: 'Einfach', normal: 'Normal', hard: 'Schwer' },
        gamemodes: { survival: 'Überleben', creative: 'Kreativ', adventure: 'Abenteuer', spectator: 'Zuschauer' },
      },
      danger: {
        title: 'Gefahrenzone',
        body: 'Löschen entfernt den Server und seine Welt endgültig. Das lässt sich nicht rückgängig machen.',
        delete: 'Server löschen',
        confirmTitle: '„{name}“ löschen?',
        confirmBody: 'Welt, Einstellungen und Konsolenverlauf werden dauerhaft entfernt. Gib zur Bestätigung den Servernamen ein.',
        confirm: 'Endgültig löschen',
        deleting: 'Lösche …',
        deleted: 'Server gelöscht',
      },
      setup: {
        title: 'Dein Server wird eingerichtet',
        steps: ['Server erstellt', 'Server-Dateien laden', 'Minecraft startet', 'Online'],
        readyTitle: 'Dein Server ist online',
        readyBody: 'Füg ihn in Minecraft hinzu und leg los.',
        stoppedTitle: 'Dein Server ist bereit',
        stoppedBody: 'Drück auf Starten, wenn du spielen willst.',
      },
      notices: {
        IDLE_STOPPED: 'Automatisch gestoppt, weil niemand online war.',
        START_FAILED: 'Der Server ist beim Starten gestoppt. Die Konsole zeigt den Grund.',
        RUNNING_LIMIT: 'Erstellt, aber nicht gestartet: Ein anderer Server lief.',
        POOL_FULL: 'Erstellt, aber nicht gestartet: Der gemeinsame Pool war voll. Versuch gleich nochmal zu starten.',
      },
      notFound: 'Diesen Server gibt es nicht oder er gehört jemand anderem.',
    },
    errors: {
      RUNNING_LIMIT: 'Es kann nur ein Server gleichzeitig laufen. Stoppe zuerst den anderen.',
      RUNNING_LIMIT_NAMED: 'Es kann nur ein Server gleichzeitig laufen. Stoppe zuerst „{name}“.',
      POOL_FULL: 'Die gemeinsame Server-Kapazität ist gerade voll. Versuch es in ein paar Minuten nochmal.',
      NO_PORTS: 'Gerade sind keine Server-Slots frei. Versuch es später nochmal.',
      PREPARING: 'Die Server-Dateien laden noch. Gleich ist er bereit.',
      SETUP_FAILED: 'Das Setup dieses Servers ist fehlgeschlagen. Lösch ihn und erstelle einen neuen.',
      NOT_RUNNING: 'Der Server läuft nicht.',
      MUST_BE_OFFLINE: 'Stoppe den Server, bevor du den Speicher änderst.',
      NOT_READY: 'Die Server-Dateien sind noch nicht bereit. Versuch es gleich nochmal.',
      BUSY: 'Der Server fährt noch herunter. Versuch es in einer Minute nochmal.',
      ADDON_INCOMPATIBLE: 'Dieser Build passt nicht zur Software oder Version des Servers.',
      ADDON_TOO_LARGE: 'Die Datei ist zu groß.',
      ADDONS_UNSUPPORTED: 'Vanilla-Server können keine Plugins oder Mods laden.',
      INVALID_LOGIN: 'Benutzername oder Passwort falsch.',
      USERNAME_TAKEN: 'Dieser Benutzername ist vergeben.',
      INVALID_USERNAME: 'Benutzernamen haben 3–20 Zeichen: Buchstaben, Zahlen, Punkt, Bindestrich oder Unterstrich.',
      INVALID_PASSWORD: 'Passwörter brauchen mindestens 8 Zeichen.',
      INVALID_NAME: 'Servernamen brauchen 2–32 Zeichen.',
      INVALID_TIER: 'Wähle eine der Speicherstufen.',
      INVALID_VERSION: 'Diese Minecraft-Version ist nicht verfügbar.',
      INVALID_SOFTWARE: 'Wähle eine Server-Software.',
      RATE_LIMITED: 'Zu viele Versuche. Warte kurz und versuch es nochmal.',
      RATE_LIMITED_WAIT: 'Zu viele Versuche. Versuch es in {min} Min. nochmal.',
      UNAUTHORIZED: 'Deine Sitzung ist abgelaufen. Bitte melde dich neu an.',
      NOT_FOUND: 'Nicht gefunden.',
      FORBIDDEN: 'Diese Anfrage wurde blockiert.',
      VALIDATION: 'Bitte prüfe deine Eingaben.',
      UPSTREAM: 'Der Server-Host hat nicht geantwortet. Versuch es gleich nochmal.',
      NETWORK: 'Keine Verbindung. Prüfe dein Internet und versuch es nochmal.',
      GENERIC: 'Etwas ist schiefgelaufen. Versuch es nochmal.',
    },
  },
  notFound: {
    code: '404',
    title: 'Dieser Chunk wurde nie generiert',
    body: 'Die Seite, die du suchst, ist nicht Teil dieser Welt.',
    home: 'Zurück zum Hafen',
    servers: 'Meine Server',
  },
}

export const COPY = { en, de }

export function interpolate(text, vars = {}) {
  return String(text).replace(/\{(\w+)\}/g, (_, key) => (vars[key] == null ? `{${key}}` : String(vars[key])))
}

export const SITE_VARS = {
  ip: SITE.ip,
  email: SITE.paypalEmail,
  site: SITE.origin.replace(/^https:\/\//, ''),
  version: SITE.minecraft,
}
