name: AetherMobs
version: 1.0.0
main: de.aetherion.aethermobs.AetherMobs
api-version: '1.21'
depend:
  - AetherionCore
  - AetherionItems
softdepend:
  - PlaceholderAPI
  - AetherionQuests

commands:

  pet:
    description: DEV pet spawner
    usage: /pet <shiny|collection|sphere|beta>
    permission: aethermobs.admin

  pets:
    description: Open your pet collection
    usage: /pets

  aetherlex:
    description: Open the Aetherlex pet encyclopedia
    usage: /aetherlex

permissions:
  aethermobs.admin:
    description: Spawn test pets
    default: op